### ISSUE TITLE
Access values without 'v' prefix

### ISSUE THREAD

**Issue by lilith** [nowsprinting/check-version-format-action#215]
I started integrating this only to realize that all the outputs include the 'v' prefix (or whatever is configured), and there's no way to turn that off. I'm running actions on both windows and linux runners, so I was hoping to avoid messy hacks.

Ideally, I'd like to be able to get the following formats out easily. It seems unexpected to add back in the configured prefix - the action user can do that easily but can't remove it quite as easily. Maybe let us have that as a configuration?

* version `1.2.3-preview1`
* major `1` 
* minor `2`
* patch `3`
* prerelease `preview1`

**Comment by nowsprinting** [comment]
> version `1.2.3-preview1`

If the version does not have a prefix, can you solve this by setting inputs.prefix to ''?

Or, if the version has a prefix, but you want to remove it in the output, We may consider adding outputs.

e.g.,
* full_without_prefix
* major_without_prefix
* major_prerelease_without_prefix

Even with prefixes, minor, patch, and prerelease are not supported, are there any cases where these are needed?

**Comment by lilith** [comment]
The version has a prefix but I want to remove it.

Minor matters, for example with v0.9.3, the major version is actually the
minor, for compat reasons. Like .NET has AssemblyVersion that should only
change for breaking changes

**Comment by nowsprinting** [comment]
Thank you for your response.

ok, I add outputs follows:

with prefix:
- minor
- patch
- prerelease

without prefix:
- full_without_prefix
- major_without_prefix
- major_prerelease_without_prefix

But,

> .NET has AssemblyVersion

Sorry. .NET support is impossible now, because this action uses [semver](https://www.npmjs.com/package/semver).

**Comment by nowsprinting** [comment]
@lilith san, plz use v3.2!
