### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon. 

### ISSUE THREAD

**Issue by marwin1991** [nowsprinting/check-version-format-action#287]
Hello, your work is awesome!!!

I notice something:

https://github.com/marwin1991/github-action/actions/runs/3451277421

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

@nowsprinting

**Comment by nowsprinting** [comment]
Thanks @marwin1991 san,

This problem was fixed in #286
But, I forget to release this!
Please wait, soon!

**Comment by nowsprinting** [comment]
Just released v3.2.4 :rocket:
Please use this version!

**Comment by marwin1991** [comment]
@nowsprinting is it tag as v3 also?

**Comment by marwin1991** [comment]
@nowsprinting I was working on https://github.com/renovatebot/github-action/pull/651
when i found your awesome tool! Maybe we can use it here too?

**Comment by nowsprinting** [comment]
Yes, you can use `@v3`.
However, v3 is a branch, not a tag, in this repository.

See https://github.com/nowsprinting/check-version-format-action/blob/master/.github/workflows/release.yml#L43-L47
