### ISSUE TITLE
Warning: The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by semack** [nowsprinting/check-version-format-action#296]
Hey,
I'm getting the following warning when the action starts

``Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/``

Could it be fixed?

Thanks,
Andriy.

**Comment by nowsprinting** [comment]
Thank you for your report!
Fix and released it.
Please use v3.2.6

**Comment by semack** [comment]
Thanks!
