### ISSUE TITLE
Use of deprecated `::set-output` in v2 of action

### ISSUE THREAD

**Issue by ErikBjare** [nowsprinting/check-version-format-action#301]
Hi, I'm using v2 of this action, and there are a bunch of warnings caused by use of deprecated `::set-output`: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Looks like all it takes is a simple `npm update` (and maybe updating/relaxing some dependencies). Would appreciate it if this could be fixed :)

**Comment by nowsprinting** [comment]
Thanks for using!
What are your reasons for not using v3?

**Comment by ErikBjare** [comment]
My version tags follow a shorter format than the semver-prescribed. Like `v0.12.3b2`.

Another option for me is to simply submit and adopt semver proper, but that would require a bit of tinkering with our build scripts.

**Comment by ErikBjare** [comment]
I forked and ran `npm update` which seems to have fixed it: https://github.com/ActivityWatch/check-version-format-action/tree/v2

Now running my own fork in my actions, so no longer an issue for me. Thanks again for this action! ❤️ 
Closing.
